import React, { useState } from 'react';
import { Download, Calendar, Search, Filter, FileQuestion } from 'lucide-react';
import { motion } from 'framer-motion';
import { useToast } from '../context/ToastContext';
import FileDropzone from './FileDropzone';

function Reports() {
  const { addToast } = useToast();
  const [searchQuery, setSearchQuery] = useState('');
  const [extractedData, setExtractedData] = useState(null);
  
  const mockReports = [
    { id: 'REP-005', date: '2023-11-20', type: 'Weekly Sales Forecast', status: 'Ready', size: '2.4 MB' },
    { id: 'PO-BATCH-004', date: '2023-11-19', type: 'Purchase Orders', status: 'Sent to ERP', size: '156 KB' },
    { id: 'REP-004', date: '2023-11-13', type: 'Weekly Sales Forecast', status: 'Ready', size: '2.3 MB' },
    { id: 'PO-BATCH-003', date: '2023-11-12', type: 'Purchase Orders', status: 'Sent to ERP', size: '142 KB' },
    { id: 'REP-003', date: '2023-11-06', type: 'Weekly Sales Forecast', status: 'Archived', size: '2.2 MB' },
  ];

  const filteredReports = mockReports.filter(r => r.id.toLowerCase().includes(searchQuery.toLowerCase()));

  const handleExport = (id) => {
    addToast(`Exporting ${id}...`, 'info');
    setTimeout(() => {
      addToast(`${id} downloaded successfully`, 'success');
    }, 1500);
  };

  const tableVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const rowVariants = {
    hidden: { opacity: 0, x: -10 },
    show: { opacity: 1, x: 0 }
  };

  return (
    <div className="page-container">
      <header className="header">
        <div>
          <h1>Reports & Exports</h1>
          <div style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>
            Download historical PDF/CSV summaries generated by FORESIGHT
          </div>
        </div>
      </header>

      <div className="chart-card" style={{ marginBottom: '2.5rem' }}>
        <h3 style={{ fontSize: '1.2rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <FileQuestion size={18} color="var(--accent-color)" /> Process New Document (AI Extraction)
        </h3>
        <FileDropzone 
          title="Upload Vendor Contract or Invoice"
          description="Drag and drop PDF or Image files to automatically extract structured data via AI"
          acceptedTypes=".pdf, image/*"
          onUploadSuccess={(file) => {
            addToast(`Successfully extracted data from ${file.name}`, 'success');
            setExtractedData({
               vendor: 'Acme Logistics Corp',
               totalAmount: '$45,200.00',
               date: new Date().toLocaleDateString(),
               confidence: '98.5%'
            });
          }}
        />
        {extractedData && (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} style={{ marginTop: '1.5rem', padding: '1.5rem', background: 'rgba(16, 185, 129, 0.05)', border: '1px solid rgba(16, 185, 129, 0.3)', borderRadius: '12px' }}>
             <h4 style={{ color: 'var(--success)', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
                Data Extracted Successfully
             </h4>
             <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', fontSize: '0.9rem' }}>
                <div><span style={{color: 'var(--text-secondary)'}}>Vendor Name:</span> <span style={{fontWeight: '600'}}>{extractedData.vendor}</span></div>
                <div><span style={{color: 'var(--text-secondary)'}}>Invoice Total:</span> <span style={{fontWeight: '600'}}>{extractedData.totalAmount}</span></div>
                <div><span style={{color: 'var(--text-secondary)'}}>Processed Date:</span> <span style={{fontWeight: '600'}}>{extractedData.date}</span></div>
                <div><span style={{color: 'var(--text-secondary)'}}>AI Confidence Score:</span> <span style={{fontWeight: '600', color: 'var(--accent-color)'}}>{extractedData.confidence}</span></div>
             </div>
             <div style={{ marginTop: '1rem', display: 'flex', justifyContent: 'flex-end', gap: '1rem' }}>
                <button className="btn btn-secondary" onClick={() => setExtractedData(null)}>Dismiss</button>
                <button className="btn btn-primary" onClick={() => { addToast('Document pushed to ERP', 'success'); setExtractedData(null); }}>Approve & Sync to ERP</button>
             </div>
          </motion.div>
        )}
      </div>

      <div className="chart-card" style={{ padding: '0', overflow: 'hidden' }}>
        <div style={{ padding: '1.5rem', borderBottom: '1px solid var(--border-color)', display: 'flex', gap: '1rem', alignItems: 'center', background: 'rgba(255,255,255,0.01)' }}>
          <div className="input-icon-wrapper" style={{ flex: 1, maxWidth: '320px' }}>
            <Search size={16} />
            <input 
              type="text" 
              className="glass-input" 
              placeholder="Search report ID..." 
              style={{ width: '100%' }}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          
          <div className="input-icon-wrapper">
            <Calendar size={16} />
            <select className="glass-select">
              <option value="30">Last 30 Days</option>
              <option value="90">Last 90 Days</option>
              <option value="all">All Time</option>
            </select>
          </div>
          
          <div className="input-icon-wrapper">
            <Filter size={16} />
            <select className="glass-select">
              <option value="">All Types</option>
              <option value="Sales">Sales Forecast</option>
              <option value="PO">Purchase Orders</option>
            </select>
          </div>
        </div>

        {filteredReports.length > 0 ? (
          <div className="table-wrapper" style={{ border: 'none', borderRadius: 0 }}>
            <table>
              <thead>
                <tr>
                  <th style={{ paddingLeft: '1.5rem' }}>Report ID</th>
                  <th>Date Generated</th>
                  <th>Type</th>
                  <th>Size</th>
                  <th>Status</th>
                  <th style={{ textAlign: 'right', paddingRight: '1.5rem' }}>Action</th>
                </tr>
              </thead>
              <motion.tbody initial="hidden" animate="show" variants={tableVariants}>
                {filteredReports.map((report) => (
                  <motion.tr key={report.id} variants={rowVariants} whileHover={{ backgroundColor: 'var(--panel-bg-hover)' }}>
                    <td style={{ paddingLeft: '1.5rem', fontWeight: '600', color: 'var(--text-primary)' }}>{report.id}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{report.date}</td>
                    <td>{report.type}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{report.size}</td>
                    <td>
                      <span className={`badge ${
                        report.status === 'Ready' ? 'badge-success' : 
                        report.status === 'Sent to ERP' ? 'badge-warning' : 
                        'badge-neutral'
                      }`}>
                        {report.status}
                      </span>
                    </td>
                    <td style={{ textAlign: 'right', paddingRight: '1.5rem' }}>
                      <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }} className="btn btn-secondary" style={{ padding: '0.4rem 0.8rem' }} onClick={() => handleExport(report.id)}>
                        <Download size={14} /> Export
                      </motion.button>
                    </td>
                  </motion.tr>
                ))}
              </motion.tbody>
            </table>
          </div>
        ) : (
          <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} className="empty-state">
            <FileQuestion size={48} />
            <h3>No reports found</h3>
            <p>We couldn't find any reports matching "{searchQuery}".</p>
            <button className="btn btn-secondary" style={{ marginTop: '1rem' }} onClick={() => setSearchQuery('')}>Clear Search</button>
          </motion.div>
        )}
      </div>
    </div>
  );
}

export default Reports;
